### ISSUE TITLE
Center align text in README file

### ISSUE THREAD

**Issue by N-dcool** [N-dcool/Leetcode-Questions#3]
I propose that the text in the README file be centered for better visual alignment and readability. This will make the information easier to understand and retain for users.

<img width="898" alt="Screenshot 2023-01-30 at 12 02 39 PM" src="https://user-images.githubusercontent.com/107427909/215405021-767676f2-4ad4-470c-826e-0ace883791d5.png">

**Comment by TankChirag-1212** [comment]
hey!!, I would like to solve this issue...please allow me to solve this issue😃

**Comment by N-dcool** [comment]
> hey!!, I would like to solve this issue...please allow me to solve this issue😃

ok @TankChirag-1212 you are assign 😄.

**Comment by N-dcool** [comment]
Thanks @TankChirag-1212 for your contribution 🙂.
